# myapp.kv

BoxLayout:
    orientation: 'vertical'


    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            source:"2.png"
            size: root.width, root.height
            pos: self.pos
    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'

        MDTextField:
            hint_text: "Username"
            size_hint_x: None
            width: "200dp"
            pos_hint: {'x': 0.4, 'y': 1}

        MDTextField:
            hint_text: "Password"
            size_hint_x: None
            width: "200dp"

        MDRaisedButton:
            text: "Login"
            on_release: app.login()

        MDRaisedButton:
            text: "Forgot Password?"
            on_release: app.forgot_password()

        MDRaisedButton:
            text: "Create Account"
            on_release: app.create_account()
